// swift-tools-version:5.9
import PackageDescription

// Committed manifest. The Swift sources for each target are GENERATED by the
// matching package's build step into packages/<layer>/dist/ios/ (gitignored),
// so `swift build` / `swift package describe` work only after `pnpm build`.
//
// Target dependencies mirror the one-way direction enforced on the web side:
//   DesignSystemIcons      -> DesignSystemTokens
//   DesignSystemComponents -> DesignSystemTokens, DesignSystemIcons

let package = Package(
    name: "design-system",
    products: [
        .library(name: "DesignSystemTokens", targets: ["DesignSystemTokens"]),
        .library(name: "DesignSystemIcons", targets: ["DesignSystemIcons"]),
        .library(name: "DesignSystemComponents", targets: ["DesignSystemComponents"]),
    ],
    targets: [
        .target(
            name: "DesignSystemTokens",
            path: "packages/tokens/dist/ios/DesignSystemTokens"
        ),
        .target(
            name: "DesignSystemIcons",
            dependencies: ["DesignSystemTokens"],
            path: "packages/icons/dist/ios/DesignSystemIcons"
        ),
        .target(
            name: "DesignSystemComponents",
            dependencies: ["DesignSystemTokens", "DesignSystemIcons"],
            path: "packages/components/dist/ios/DesignSystemComponents"
        ),
    ]
)
