import {
  parseTypographyToken,
  renderTypographySwift,
  resolveTypography,
  validateTypographyFontFiles,
} from "../src/typography.js";
import { describe, expect, it } from "vitest";
import {
  cssVarName,
  parseLengthToPoints,
  renderCss,
  renderSwift,
} from "../src/generate.js";
import { fontImports } from "../src/fonts.js";
import { tokens } from "../src/tokens/index.js";
import {
  parseTypographyToken,
  renderTypographySwift,
  resolveTypography,
} from "../src/typography.js";
import type { Tokens } from "../src/types.js";
import { allAxes, mixedEmpty, nestedOrderA, nestedOrderB } from "./fixtures.js";

describe("cssVarName", () => {
  it("prefixes and kebab-cases", () => {
    expect(cssVarName("type.p")).toBe("--ds-type-p");
    expect(cssVarName("fontFamilyBase")).toBe("--ds-font-family-base");
    expect(cssVarName("color.bg")).toBe("--ds-color-bg");
    expect(cssVarName("layout.focus-ring-width")).toBe(
      "--ds-layout-focus-ring-width",
    );
  });
});

describe("renderCss — real token source", () => {
  const css = renderCss(tokens);

  it("marks the file as generated", () => {
    expect(
      css.startsWith("/* Generated by @design-system/tokens. Do not edit. */"),
    ).toBe(true);
  });

  it("emits the font @import directly under the header, before any rule", () => {
    const lines = css.split("\n");
    expect(lines[0]).toBe(
      "/* Generated by @design-system/tokens. Do not edit. */",
    );
    expect(lines[1]).toBe(fontImports[0]);
    expect(lines[1]).toMatch(
      /^@import url\("https:\/\/fonts\.googleapis\.com\//,
    );
    // nothing but the header may precede an @import
    expect(css.indexOf("@import")).toBeLessThan(css.indexOf("{"));
  });

  it("emits every category's base values in :root", () => {
    expect(css).toMatch(
      /:root \{[^}]*--ds-type-p: normal normal 400 1rem\/1\.625 'Public Sans', sans-serif;/,
    );
    expect(css).toMatch(/:root \{[^}]*--ds-space-200: 1rem;/);
    expect(css).toMatch(/:root \{[^}]*--ds-radius-300: 8px;/);
    expect(css).toMatch(/:root \{[^}]*--ds-layout-gutter: 1rem;/);
    expect(css).toMatch(/:root \{[^}]*--ds-color-bg: #fbfcfc;/);
  });

  it("emits a `type` font shorthand verbatim, commas included", () => {
    expect(css).toContain(
      "--ds-type-overline: normal normal 500 0.75rem/1.33 'IBM Plex Mono', ui-monospace, monospace;",
    );
  });

  it("resolves colour values to literals and emits no --ds-palette-* variable", () => {
    expect(css).not.toContain("--ds-palette");
    expect(css).toMatch(/--ds-color-bg: #fbfcfc;/);
    expect(css).toMatch(/\[data-theme="dark"\] \{[^}]*--ds-color-bg: #0b1210;/);
  });

  it("emits responsive and triple-nested color overrides", () => {
    expect(css).toMatch(
      /@media \(min-width: 768px\) \{\n {2}:root \{[^}]*--ds-layout-gutter: 1\.5rem;/,
    );
    expect(css).toMatch(
      /@media \(min-width: 768px\) \{\n {2}:root \{[^}]*--ds-color-bg: #f1f5f3;/,
    );
    expect(css).toMatch(
      /@media \(min-width: 768px\) \{\n {2}\[data-theme="dark"\] \.ds-scope-compact \{\n {4}--ds-color-bg: #101815;/,
    );
    expect(css).toMatch(/\.ds-scope-compact \{\n {2}--ds-color-bg: #eff6f3;/);
    expect(css.indexOf("@media (min-width: 768px)")).toBeLessThan(
      css.indexOf("@media (min-width: 1024px)"),
    );
  });

  it("is deterministic and independent of authoring order", () => {
    expect(renderCss(tokens)).toBe(css);
    const a: Tokens = { "x.t": nestedOrderA };
    const b: Tokens = { "x.t": nestedOrderB };
    expect(renderCss(a)).toBe(renderCss(b));
  });
});

describe("renderCss — every axis and combination (synthetic)", () => {
  const css = renderCss({ "space.t": allAxes });

  it("wraps each condition-set in the contract's selector block", () => {
    expect(css).toMatch(/\[data-theme="dark"\] \{/);
    expect(css).toMatch(/@media \(min-width: 768px\) \{\n {2}:root \{/);
    expect(css).toMatch(/\n\.ds-scope-compact \{/);
    expect(css).toMatch(/\[data-theme="dark"\] \.ds-scope-compact \{/);
  });

  it("orders blocks by non-decreasing selector specificity", () => {
    const order = [
      '[data-theme="dark"] {',
      "@media (min-width: 768px) {",
      ".ds-scope-compact {",
      '[data-theme="dark"] .ds-scope-compact {',
    ];
    const positions = order.map((s) => css.indexOf(s));
    expect(positions.every((p) => p >= 0)).toBe(true);
    for (let i = 1; i < positions.length; i++) {
      expect(positions[i]).toBeGreaterThan(positions[i - 1]!);
    }
  });
});

describe("renderCss — empty / well-formed", () => {
  it("produces a header + font @import + :root {} for no tokens", () => {
    const css = renderCss({});
    expect(css).toBe(
      `/* Generated by @design-system/tokens. Do not edit. */\n${fontImports[0]}\n:root {}\n`,
    );
  });

  it("succeeds when one category is empty and another is not", () => {
    const css = renderCss(mixedEmpty);
    expect(css).toContain("--ds-space-md: 1rem;");
    expect(css).not.toMatch(/undefined/);
  });
});

describe("parseLengthToPoints", () => {
  it("converts rem to points at 1rem = 16pt", () => {
    expect(parseLengthToPoints("1.5rem")).toBe(24);
    expect(parseLengthToPoints("0.25rem")).toBe(4);
  });

  it("converts px to points 1:1", () => {
    expect(parseLengthToPoints("4px")).toBe(4);
    expect(parseLengthToPoints("44px")).toBe(44);
  });

  it("returns undefined for units with no fixed point equivalent", () => {
    expect(parseLengthToPoints("68ch")).toBeUndefined();
  });
});

describe("renderSwift", () => {
  it("emits typography constants unchanged (String, base value only)", () => {
    const swift = renderSwift(tokens);
    expect(swift).toMatch(
      /public static let typeP: String = "normal normal 400 1rem\/1\.625 'Public Sans', sans-serif"/,
    );
    expect(swift).not.toMatch(/public static let [a-z]+\.[a-z]/);
  });

  it("emits space/radius/layout length tokens as CGFloat points", () => {
    const swift = renderSwift(tokens);
    expect(swift).toMatch(/public static let space300: CGFloat = 24/);
    expect(swift).toMatch(/public static let radius200: CGFloat = 4/);
    expect(swift).toMatch(/public static let layoutFocusRingWidth: CGFloat = 3/);
    expect(swift).toMatch(/public static let layoutTouchMin: CGFloat = 44/);
  });

  it("keeps a length with no point equivalent (e.g. `ch`) as a String", () => {
    expect(renderSwift(tokens)).toMatch(
      /public static let layoutMeasure: String = "68ch"/,
    );
  });

  it("emits color tokens as a dynamic light/dark SwiftUI Color", () => {
    const swift = renderSwift(tokens);
    expect(swift).toMatch(
      /public static let colorBg: Color = dsColor\(light: "#fbfcfc", dark: "#0b1210"\)/,
    );
    expect(swift).toMatch(
      /public static let colorPrimary: Color = dsColor\(light: "#04724d", dark: "#55e39b"\)/,
    );
  });

  it("includes the SwiftUI/UIKit imports and the dsColor helper once", () => {
    const swift = renderSwift(tokens);
    expect(swift).toContain("import SwiftUI");
    expect(swift).toContain("import UIKit");
    expect(swift.match(/private func dsColor/g)).toHaveLength(1);
  });

  it("still produces a valid namespace enum for no tokens", () => {
    const swift = renderSwift({});
    expect(swift).toContain("public enum DesignSystemTokens {");
    expect(swift.trim().endsWith("}")).toBe(true);
  });
});

describe("native typography projection", () => {
  it("maps all ten source roles into native font descriptors", () => {
    const styles = resolveTypography(tokens);
    expect(styles.map((style) => style.role)).toEqual([
      "display",
      "h1",
      "h2",
      "h3",
      "h4",
      "p",
      "p-sm",
      "label",
      "caption",
      "overline",
    ]);
    expect(styles[0]).toMatchObject({
      fontName: "BricolageGrotesque-96ptExtraBold_ExtraBold",
      pointSize: 40,
      weight: 800,
    });
    expect(styles[5]).toMatchObject({
      fontName: "PublicSansRoman-Regular",
      pointSize: 16,
      weight: 400,
    });
    expect(styles[9]).toMatchObject({
      fontName: "IBMPlexMono-Medium",
      pointSize: 12,
      weight: 500,
    });
  });

  it("renders deterministic Swift descriptors and preserves role identifiers", () => {
    const styles = resolveTypography(tokens);
    expect(renderTypographySwift(styles)).toBe(renderTypographySwift(styles));
    expect(renderTypographySwift(styles)).toContain("public static let pSm");
    expect(renderTypographySwift(styles)).toContain(
      "lineHeightMultiplier: 1.53",
    );
  });

  it("rejects malformed shorthand, unknown families, and unsupported weights", () => {
    expect(() => parseTypographyToken("body", "16px Public Sans")).toThrow(
      /unsupported typography shorthand/,
    );
    expect(() =>
      parseTypographyToken(
        "body",
        "normal normal 400 1rem/1.5 'Unknown Sans', sans-serif",
      ),
    ).toThrow(/unsupported font family/);
    expect(() =>
      parseTypographyToken(
        "body",
        "normal normal 450 1rem/1.5 'Public Sans', sans-serif",
      ),
    ).toThrow(/unsupported font weight/);
  });

  it("rejects missing source font files before emitting output", () => {
    const styles = resolveTypography(tokens);
    expect(() => validateTypographyFontFiles(styles, [])).toThrow(
      /No licensed iOS font files/,
    );
    expect(() => validateTypographyFontFiles(styles, ["fonts/Other.ttf"])).toThrow(
      /no source font file/,
    );
  });
});
