import { describe, expect, it } from "vitest";
import { cssVarName, renderCss, renderSwift } from "../src/generate.js";
import { fontImports } from "../src/fonts.js";
import { tokens } from "../src/tokens/index.js";
import type { Tokens } from "../src/types.js";
import { allAxes, mixedEmpty, nestedOrderA, nestedOrderB } from "./fixtures.js";

describe("cssVarName", () => {
  it("prefixes and kebab-cases", () => {
    expect(cssVarName("type.p")).toBe("--ds-type-p");
    expect(cssVarName("fontFamilyBase")).toBe("--ds-font-family-base");
    expect(cssVarName("color.bg")).toBe("--ds-color-bg");
    expect(cssVarName("layout.focus-ring-width")).toBe("--ds-layout-focus-ring-width");
  });
});

describe("renderCss — real token source", () => {
  const css = renderCss(tokens);

  it("marks the file as generated", () => {
    expect(css.startsWith("/* Generated by @design-system/tokens. Do not edit. */")).toBe(true);
  });

  it("emits the font @import directly under the header, before any rule", () => {
    const lines = css.split("\n");
    expect(lines[0]).toBe("/* Generated by @design-system/tokens. Do not edit. */");
    expect(lines[1]).toBe(fontImports[0]);
    expect(lines[1]).toMatch(/^@import url\("https:\/\/fonts\.googleapis\.com\//);
    // nothing but the header may precede an @import
    expect(css.indexOf("@import")).toBeLessThan(css.indexOf("{"));
  });

  it("emits every category's base values in :root", () => {
    expect(css).toMatch(/:root \{[^}]*--ds-type-p: normal normal 400 1rem\/1\.625 'Public Sans', sans-serif;/);
    expect(css).toMatch(/:root \{[^}]*--ds-space-200: 1rem;/);
    expect(css).toMatch(/:root \{[^}]*--ds-radius-300: 8px;/);
    expect(css).toMatch(/:root \{[^}]*--ds-layout-gutter: 1rem;/);
    expect(css).toMatch(/:root \{[^}]*--ds-color-bg: #fbfcfc;/);
  });

  it("emits a `type` font shorthand verbatim, commas included", () => {
    expect(css).toContain(
      "--ds-type-overline: normal normal 500 0.75rem/1.33 'IBM Plex Mono', ui-monospace, monospace;",
    );
  });

  it("resolves colour values to literals and emits no --ds-palette-* variable", () => {
    expect(css).not.toContain("--ds-palette");
    expect(css).toMatch(/--ds-color-bg: #fbfcfc;/);
    expect(css).toMatch(/\[data-theme="dark"\] \{[^}]*--ds-color-bg: #0b1210;/);
  });

  it("emits responsive and triple-nested color overrides", () => {
    expect(css).toMatch(/@media \(min-width: 768px\) \{\n {2}:root \{[^}]*--ds-layout-gutter: 1\.5rem;/);
    expect(css).toMatch(/@media \(min-width: 768px\) \{\n {2}:root \{[^}]*--ds-color-bg: #f1f5f3;/);
    expect(css).toMatch(/@media \(min-width: 768px\) \{\n {2}\[data-theme="dark"\] \.ds-scope-compact \{\n {4}--ds-color-bg: #101815;/);
    expect(css).toMatch(/\.ds-scope-compact \{\n {2}--ds-color-bg: #eff6f3;/);
    expect(css.indexOf("@media (min-width: 768px)")).toBeLessThan(
      css.indexOf("@media (min-width: 1024px)"),
    );
  });

  it("is deterministic and independent of authoring order", () => {
    expect(renderCss(tokens)).toBe(css);
    const a: Tokens = { "x.t": nestedOrderA };
    const b: Tokens = { "x.t": nestedOrderB };
    expect(renderCss(a)).toBe(renderCss(b));
  });
});

describe("renderCss — every axis and combination (synthetic)", () => {
  const css = renderCss({ "space.t": allAxes });

  it("wraps each condition-set in the contract's selector block", () => {
    expect(css).toMatch(/\[data-theme="dark"\] \{/);
    expect(css).toMatch(/@media \(min-width: 768px\) \{\n {2}:root \{/);
    expect(css).toMatch(/\n\.ds-scope-compact \{/);
    expect(css).toMatch(/\[data-theme="dark"\] \.ds-scope-compact \{/);
  });

  it("orders blocks by non-decreasing selector specificity", () => {
    const order = [
      '[data-theme="dark"] {',
      "@media (min-width: 768px) {",
      ".ds-scope-compact {",
      '[data-theme="dark"] .ds-scope-compact {',
    ];
    const positions = order.map((s) => css.indexOf(s));
    expect(positions.every((p) => p >= 0)).toBe(true);
    for (let i = 1; i < positions.length; i++) {
      expect(positions[i]).toBeGreaterThan(positions[i - 1]!);
    }
  });
});

describe("renderCss — empty / well-formed", () => {
  it("produces a header + font @import + :root {} for no tokens", () => {
    const css = renderCss({});
    expect(css).toBe(
      `/* Generated by @design-system/tokens. Do not edit. */\n${fontImports[0]}\n:root {}\n`,
    );
  });

  it("succeeds when one category is empty and another is not", () => {
    const css = renderCss(mixedEmpty);
    expect(css).toContain("--ds-space-md: 1rem;");
    expect(css).not.toMatch(/undefined/);
  });
});

describe("renderSwift", () => {
  it("emits base-value constants with sanitised camelCase identifiers", () => {
    const swift = renderSwift(tokens);
    expect(swift).toMatch(
      /public static let typeP: String = "normal normal 400 1rem\/1\.625 'Public Sans', sans-serif"/,
    );
    expect(swift).toMatch(/public static let colorBg: String = "#fbfcfc"/);
    expect(swift).toMatch(/public static let layoutFocusRingWidth: String = "3px"/);
    expect(swift).not.toMatch(/public static let [a-z]+\.[a-z]/);
  });

  it("still produces a valid namespace enum for no tokens", () => {
    const swift = renderSwift({});
    expect(swift).toContain("public enum DesignSystemTokens {");
    expect(swift.trim().endsWith("}")).toBe(true);
  });
});
