import { describe, it, expect } from "vitest";
import { renderCss, renderSwift, cssVarName } from "../src/generate.js";
import { tokens, breakpoints } from "../src/tokens/index.js";
import type { Tokens } from "../src/types.js";

describe("cssVarName", () => {
  it("prefixes and kebab-cases", () => {
    expect(cssVarName("placeholder")).toBe("--ds-placeholder");
    expect(cssVarName("fontFamilyBase")).toBe("--ds-font-family-base");
    expect(cssVarName("color.bg")).toBe("--ds-color-bg");
  });
});

describe("renderCss — real token source", () => {
  const css = renderCss(tokens, breakpoints);

  it("emits the placeholder token in :root with its source value", () => {
    expect(css).toMatch(/:root \{[^}]*--ds-placeholder: 0;/);
  });

  it("marks the file as generated", () => {
    expect(css.startsWith("/* Generated by @design-system/tokens. Do not edit. */")).toBe(true);
  });

  it("is deterministic", () => {
    expect(renderCss(tokens, breakpoints)).toBe(css);
  });
});

describe("renderCss — all variant axes", () => {
  const fixture: Tokens = {
    gap: {
      value: "1rem",
      breakpoints: { md: "1.5rem" },
      colorModes: { dark: "0.75rem" },
      features: { compact: "0.5rem" },
    },
  };
  const css = renderCss(fixture, { md: "48rem" });

  it("emits a @media block for the breakpoint axis", () => {
    expect(css).toMatch(/@media \(min-width: 48rem\) \{\s*:root \{[^}]*--ds-gap: 1\.5rem;/);
  });

  it("emits a [data-theme=dark] block for the color-mode axis", () => {
    expect(css).toMatch(/\[data-theme="dark"\] \{[^}]*--ds-gap: 0\.75rem;/);
  });

  it("emits a .ds-feature-* block for the feature axis", () => {
    expect(css).toMatch(/\.ds-feature-compact \{[^}]*--ds-gap: 0\.5rem;/);
  });
});

describe("empty-but-well-formed", () => {
  it("renderCss on no tokens still produces a valid :root {} block", () => {
    const css = renderCss({}, {});
    expect(css).toContain(":root {}");
    expect(css).not.toMatch(/undefined/);
  });

  it("renderSwift on no tokens still produces a valid namespace enum", () => {
    const swift = renderSwift({});
    expect(swift).toContain("public enum DesignSystemTokens {");
    expect(swift.trim().endsWith("}")).toBe(true);
  });
});

describe("renderSwift — real token source", () => {
  it("emits the placeholder constant mirroring the web value", () => {
    const swift = renderSwift(tokens);
    expect(swift).toMatch(/public static let placeholder: Double = 0/);
  });
});
