/**
 * Custom token generator (not Style Dictionary).
 *
 * Reads the assembled token source and emits:
 *   - dist/web/tokens.css   CSS custom properties, in scoped selector blocks
 *                           ordered by ascending specificity
 *   - dist/ios/DesignSystemTokens/Tokens.swift   Swift base-value constants
 *
 * The typed JS entry (dist/web/index.js + .d.ts) is emitted by `tsc` from
 * src/, so this file only owns the CSS and Swift projections.
 *
 * Output is deterministic: the same source produces byte-identical files,
 * regardless of the order overrides were authored in.
 */
import { mkdirSync, writeFileSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { fontImports } from "./fonts.js";
import { resolveTokens } from "./resolve.js";
import { tokens } from "./tokens/index.js";
import type { ConditionSet, Tokens } from "./types.js";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");
const webDir = join(pkgRoot, "dist", "web");
const iosDir = join(pkgRoot, "dist", "ios", "DesignSystemTokens");

const HEADER = "/* Generated by @design-system/tokens. Do not edit. */";

/** `fontFamily` -> `--ds-font-family`, `type.body` -> `--ds-type-body`. */
export function cssVarName(key: string): string {
  return `--ds-${key
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[._]/g, "-")
    .toLowerCase()}`;
}

interface Wrapper {
  /** identity key for merging adjacent rules into one block */
  key: string;
  open: string[];
  close: string[];
  /** indentation for declarations inside the block */
  indent: string;
}

/**
 * The CSS block a condition-set is emitted into. `colorMode: "light"` never
 * produces its own `[data-theme]` selector — light is the default surface, so
 * it folds into `:root` (or simply omits the attribute when combined).
 */
function wrapperFor(c: ConditionSet): Wrapper {
  const media = c.minWidth !== undefined ? `@media (min-width: ${c.minWidth}px)` : null;
  const selectorParts: string[] = [];
  if (c.colorMode === "dark") selectorParts.push('[data-theme="dark"]');
  if (c.scope !== undefined) selectorParts.push(`.ds-scope-${c.scope}`);
  const selector = selectorParts.length > 0 ? selectorParts.join(" ") : ":root";
  const key = `${media ?? ""}||${selector}`;
  if (media) {
    return {
      key,
      open: [`${media} {`, `  ${selector} {`],
      close: ["  }", "}"],
      indent: "    ",
    };
  }
  return { key, open: [`${selector} {`], close: ["}"], indent: "  " };
}

export function renderCss(tokenSet: Tokens): string {
  const rules = resolveTokens(tokenSet);
  // `@import` must precede every rule (only a comment may come before it), so
  // the font imports sit directly under the header.
  const lines: string[] = [HEADER, ...fontImports];

  if (rules.length === 0) {
    lines.push(":root {}");
    return `${lines.join("\n")}\n`;
  }

  interface Block {
    wrapper: Wrapper;
    decls: Map<string, string>;
  }
  const blocks: Block[] = [];
  for (const rule of rules) {
    const wrapper = wrapperFor(rule.conditions);
    let block = blocks[blocks.length - 1];
    if (block === undefined || block.wrapper.key !== wrapper.key) {
      block = { wrapper, decls: new Map<string, string>() };
      blocks.push(block);
    }
    // Map.set keeps the last write, so a more specific rule sharing a wrapper
    // (e.g. a `light` override folded into `:root`) wins.
    block.decls.set(cssVarName(rule.name), String(rule.value));
  }

  for (const block of blocks) {
    lines.push("");
    lines.push(...block.wrapper.open);
    for (const [name, value] of block.decls) {
      lines.push(`${block.wrapper.indent}${name}: ${value};`);
    }
    lines.push(...block.wrapper.close);
  }

  return `${lines.join("\n")}\n`;
}

/** `type.body` -> `typeBody`, `color.bg` -> `colorBg`. */
function swiftIdentifier(key: string): string {
  return key
    .replace(/[._-]+([A-Za-z0-9])/g, (_m, c: string) => c.toUpperCase())
    .replace(/[^A-Za-z0-9]/g, "");
}

export function renderSwift(tokenSet: Tokens): string {
  const lines = Object.entries(tokenSet).map(([key, token]) => {
    const isNum = typeof token.value === "number";
    const swiftType = isNum ? "Double" : "String";
    const val = isNum ? String(token.value) : JSON.stringify(token.value);
    const doc = token.description ? `    /// ${token.description}\n` : "";
    return `${doc}    public static let ${swiftIdentifier(key)}: ${swiftType} = ${val}`;
  });
  const body = lines.length > 0 ? `\n${lines.join("\n")}\n` : "\n";
  return `// Generated by @design-system/tokens. Do not edit.\n\npublic enum DesignSystemTokens {${body}}\n`;
}

export function generate(): void {
  // Runs before `tsc`, so it owns the whole dist/ tree.
  rmSync(join(pkgRoot, "dist"), { recursive: true, force: true });
  mkdirSync(webDir, { recursive: true });
  mkdirSync(iosDir, { recursive: true });

  writeFileSync(join(webDir, "tokens.css"), renderCss(tokens), "utf8");
  writeFileSync(join(iosDir, "Tokens.swift"), renderSwift(tokens), "utf8");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  generate();
  const count = Object.keys(tokens).length;
  console.log(`@design-system/tokens: generated CSS + Swift for ${count} token(s)`);
}
