/**
 * Custom token generator.
 *
 * Reads the TypeScript token sources and emits web artifacts:
 *   - dist/variables.css  — CSS custom properties, with color-mode scoping
 *   - dist/manifest.json  — serialized token set for docs/tooling
 *
 * Color modes are attribute-scoped: semantic tokens are (re)declared inside
 * `:root`, `[data-color-mode="<mode>"]`, and a `prefers-color-scheme` fallback,
 * so consumers switch modes by toggling `data-color-mode` on a root element.
 * `color-scheme` is kept in sync for native UI (form controls, scrollbars).
 *
 * (Breakpoint/feature variants and iOS Swift output come in later phases.)
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { groups } from "./tokens";
import {
  COLOR_MODES,
  DEFAULT_COLOR_MODE,
  type ColorMode,
  type PrimitiveGroup,
  type SemanticGroup,
} from "./types";
import type {
  TokenManifest,
  TokenManifestEntry,
  TokenManifestGroup,
} from "./manifest";

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = join(__dirname, "..", "dist");

const cssVarName = (prefix: string, key: string) => `--${prefix}-${key}`;
const decl = (name: string, value: string) => `  ${name}: ${value};`;

const primitiveGroups = groups.filter(
  (g): g is PrimitiveGroup => g.kind === "primitive",
);
const semanticGroups = groups.filter(
  (g): g is SemanticGroup => g.kind === "semantic",
);

/** Resolve a primitive key to its raw value, for manifest display. */
function primitiveLookup(): Map<string, string> {
  const map = new Map<string, string>();
  for (const group of primitiveGroups) {
    for (const [key, value] of Object.entries(group.tokens)) {
      map.set(`${group.name}:${key}`, value);
    }
  }
  return map;
}

const lookup = primitiveLookup();

function resolveRef(prefix: string, ref: string): string {
  const value = lookup.get(`${prefix}:${ref}`);
  if (value === undefined) {
    throw new Error(
      `Semantic token references unknown primitive "${prefix}:${ref}".`,
    );
  }
  return value;
}

function buildManifest(): TokenManifest {
  const manifestGroups: TokenManifestGroup[] = groups.map((group) => {
    let tokens: TokenManifestEntry[];
    if (group.kind === "primitive") {
      tokens = Object.entries(group.tokens).map(([key, value]) => {
        const cssVar = cssVarName(group.name, key);
        return {
          kind: "primitive",
          key,
          cssVar,
          cssRef: `var(${cssVar})`,
          value,
        };
      });
    } else {
      tokens = Object.entries(group.tokens).map(([key, modeMap]) => {
        const cssVar = cssVarName(group.name, key);
        const modes = {} as Record<ColorMode, { ref: string; value: string }>;
        for (const mode of COLOR_MODES) {
          const ref = modeMap[mode];
          modes[mode] = { ref, value: resolveRef(group.name, ref) };
        }
        return {
          kind: "semantic",
          key,
          cssVar,
          cssRef: `var(${cssVar})`,
          modes,
        };
      });
    }
    return {
      name: group.name,
      category: group.category,
      kind: group.kind,
      tokens,
    };
  });

  return {
    modes: [...COLOR_MODES],
    defaultMode: DEFAULT_COLOR_MODE,
    groups: manifestGroups,
  };
}

/** `color-scheme` value for a mode (only the two native schemes are valid). */
function colorSchemeFor(mode: ColorMode): string | null {
  return mode === "light" || mode === "dark" ? mode : null;
}

function primitiveDecls(): string[] {
  return primitiveGroups.flatMap((group) =>
    Object.entries(group.tokens).map(([key, value]) =>
      decl(cssVarName(group.name, key), value),
    ),
  );
}

/** Semantic declarations resolved for a single mode (aliases -> var refs). */
function semanticDecls(mode: ColorMode): string[] {
  return semanticGroups.flatMap((group) =>
    Object.entries(group.tokens).map(([key, modeMap]) =>
      decl(cssVarName(group.name, key), `var(${cssVarName(group.name, modeMap[mode])})`),
    ),
  );
}

function buildCss(): string {
  const blocks: string[] = [
    "/* Generated by @design-system/tokens — do not edit by hand. */",
  ];

  const scheme = colorSchemeFor(DEFAULT_COLOR_MODE);
  const rootDecls = [
    ...primitiveDecls(),
    ...semanticDecls(DEFAULT_COLOR_MODE),
    ...(scheme ? [decl("color-scheme", scheme)] : []),
  ];
  blocks.push(`:root {\n${rootDecls.join("\n")}\n}`);

  // One explicit block per mode so nested overrides work (a dark subtree can
  // contain a light island via [data-color-mode="light"], and vice versa).
  for (const mode of COLOR_MODES) {
    const modeScheme = colorSchemeFor(mode);
    const modeDecls = [
      ...semanticDecls(mode),
      ...(modeScheme ? [decl("color-scheme", modeScheme)] : []),
    ];
    blocks.push(`[data-color-mode="${mode}"] {\n${modeDecls.join("\n")}\n}`);
  }

  // Follow the OS preference when no explicit mode is set (and not forced light).
  if ((COLOR_MODES as readonly string[]).includes("dark")) {
    const darkDecls = [
      ...semanticDecls("dark"),
      ...(colorSchemeFor("dark") ? [decl("color-scheme", "dark")] : []),
    ].map((d) => `  ${d}`);
    blocks.push(
      `@media (prefers-color-scheme: dark) {\n  :root:not([data-color-mode="light"]) {\n${darkDecls.join(
        "\n",
      )}\n  }\n}`,
    );
  }

  return blocks.join("\n\n") + "\n";
}

async function main() {
  const manifest = buildManifest();
  const css = buildCss();

  await mkdir(distDir, { recursive: true });
  await Promise.all([
    writeFile(join(distDir, "variables.css"), css, "utf8"),
    writeFile(
      join(distDir, "manifest.json"),
      JSON.stringify(manifest, null, 2) + "\n",
      "utf8",
    ),
  ]);

  const tokenCount = manifest.groups.reduce(
    (sum, g) => sum + g.tokens.length,
    0,
  );
  console.log(
    `Generated ${tokenCount} tokens across ${manifest.groups.length} group(s), modes: ${manifest.modes.join(
      ", ",
    )} -> ${distDir}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
