/**
 * Custom token generator (not Style Dictionary).
 *
 * Reads the assembled token source and emits:
 *   - dist/web/tokens.css   CSS custom properties, in scoped selector blocks
 *                           ordered by ascending specificity
 *   - dist/ios/DesignSystemTokens/Tokens.swift   Swift base-value constants
 *
 * The typed JS entry (dist/web/index.js + .d.ts) is emitted by `tsc` from
 * src/, so this file only owns the CSS and Swift projections.
 *
 * Output is deterministic: the same source produces byte-identical files,
 * regardless of the order overrides were authored in.
 */
import {
  mkdirSync,
  writeFileSync,
  rmSync,
  readdirSync,
  copyFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { fontImports } from "./fonts.js";
import { resolveTokens } from "./resolve.js";
import {
  renderTypographySwift,
  resolveTypography,
  validateTypographyFontFiles,
} from "./typography.js";
import { tokens } from "./tokens/index.js";
import type { ConditionSet, ResolvedRule, TokenValue, Tokens } from "./types.js";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");
const webDir = join(pkgRoot, "dist", "web");
const iosDir = join(pkgRoot, "dist", "ios", "DesignSystemTokens");
const fontSourceDir = join(pkgRoot, "src", "fonts");
const fontOutputDir = join(iosDir, "Fonts");
const iosSourceDir = join(pkgRoot, "src", "ios");

const HEADER = "/* Generated by @design-system/tokens. Do not edit. */";

/** `fontFamily` -> `--ds-font-family`, `type.body` -> `--ds-type-body`. */
export function cssVarName(key: string): string {
  return `--ds-${key
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[._]/g, "-")
    .toLowerCase()}`;
}

interface Wrapper {
  /** identity key for merging adjacent rules into one block */
  key: string;
  open: string[];
  close: string[];
  /** indentation for declarations inside the block */
  indent: string;
}

/**
 * The CSS block a condition-set is emitted into. `colorMode: "light"` never
 * produces its own `[data-theme]` selector — light is the default surface, so
 * it folds into `:root` (or simply omits the attribute when combined).
 */
function wrapperFor(c: ConditionSet): Wrapper {
  const media =
    c.minWidth !== undefined ? `@media (min-width: ${c.minWidth}px)` : null;
  const selectorParts: string[] = [];
  if (c.colorMode === "dark") selectorParts.push('[data-theme="dark"]');
  if (c.scope !== undefined) selectorParts.push(`.ds-scope-${c.scope}`);
  const selector = selectorParts.length > 0 ? selectorParts.join(" ") : ":root";
  const key = `${media ?? ""}||${selector}`;
  if (media) {
    return {
      key,
      open: [`${media} {`, `  ${selector} {`],
      close: ["  }", "}"],
      indent: "    ",
    };
  }
  return { key, open: [`${selector} {`], close: ["}"], indent: "  " };
}

export function renderCss(tokenSet: Tokens): string {
  const rules = resolveTokens(tokenSet);
  // `@import` must precede every rule (only a comment may come before it), so
  // the font imports sit directly under the header.
  const lines: string[] = [HEADER, ...fontImports];

  if (rules.length === 0) {
    lines.push(":root {}");
    return `${lines.join("\n")}\n`;
  }

  interface Block {
    wrapper: Wrapper;
    decls: Map<string, string>;
  }
  const blocks: Block[] = [];
  for (const rule of rules) {
    const wrapper = wrapperFor(rule.conditions);
    let block = blocks[blocks.length - 1];
    if (block === undefined || block.wrapper.key !== wrapper.key) {
      block = { wrapper, decls: new Map<string, string>() };
      blocks.push(block);
    }
    // Map.set keeps the last write, so a more specific rule sharing a wrapper
    // (e.g. a `light` override folded into `:root`) wins.
    block.decls.set(cssVarName(rule.name), String(rule.value));
  }

  for (const block of blocks) {
    lines.push("");
    lines.push(...block.wrapper.open);
    for (const [name, value] of block.decls) {
      lines.push(`${block.wrapper.indent}${name}: ${value};`);
    }
    lines.push(...block.wrapper.close);
  }

  return `${lines.join("\n")}\n`;
}

/** `type.body` -> `typeBody`, `color.bg` -> `colorBg`. */
function swiftIdentifier(key: string): string {
  return key
    .replace(/[._-]+([A-Za-z0-9])/g, (_m, c: string) => c.toUpperCase())
    .replace(/[^A-Za-z0-9]/g, "");
}

const REM = /^(-?[0-9]*\.?[0-9]+)rem$/;
const PX = /^(-?[0-9]*\.?[0-9]+)px$/;

/**
 * Parse a `rem`/`px` CSS length into iOS points (1rem = 16pt, 1px = 1pt, per
 * the space/radius/layout token comments). Returns `undefined` for units with
 * no fixed point equivalent (e.g. `ch`) — those stay `String` in Swift output.
 */
export function parseLengthToPoints(value: TokenValue): number | undefined {
  if (typeof value === "number") return value;
  const rem = REM.exec(value);
  if (rem) return Number(rem[1]) * 16;
  const px = PX.exec(value);
  if (px) return Number(px[1]);
  return undefined;
}

/** The plain (no min-width, no scope) value for one axis of a token's rules. */
function pickRule(
  rules: ResolvedRule[],
  match: (c: ConditionSet) => boolean,
): TokenValue | undefined {
  return rules.find((r) => match(r.conditions))?.value;
}

const SWIFT_COLOR_PRELUDE = `
import SwiftUI
import UIKit

/// Resolves per the active color scheme, mirroring the web generator's
/// \`[data-theme="dark"]\` override — the light/dark pair a color token
/// carries (\`src/tokens/color.ts\`) becomes a single dynamic \`Color\` here
/// instead of only ever emitting the light value.
private func dsColor(light: String, dark: String) -> Color {
    Color(UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(dsHex: dark) : UIColor(dsHex: light)
    })
}

private extension UIColor {
    convenience init(dsHex hex: String) {
        var value: UInt64 = 0
        Scanner(string: hex.trimmingCharacters(in: CharacterSet(charactersIn: "#")))
            .scanHexInt64(&value)
        self.init(
            red: CGFloat((value & 0xFF0000) >> 16) / 255,
            green: CGFloat((value & 0x00FF00) >> 8) / 255,
            blue: CGFloat(value & 0x0000FF) / 255,
            alpha: 1
        )
    }
}
`;

export function renderSwift(tokenSet: Tokens): string {
  const rulesByName = new Map<string, ResolvedRule[]>();
  for (const rule of resolveTokens(tokenSet)) {
    const list = rulesByName.get(rule.name) ?? [];
    list.push(rule);
    rulesByName.set(rule.name, list);
  }

  const lines = Object.entries(tokenSet).map(([key, token]) => {
    const category = key.split(".", 1)[0];
    const doc = token.description ? `    /// ${token.description}\n` : "";
    const identifier = swiftIdentifier(key);

    if (category === "color") {
      const rules = rulesByName.get(key) ?? [];
      const light =
        pickRule(
          rules,
          (c) => c.colorMode === undefined && c.minWidth === undefined && c.scope === undefined,
        ) ?? token.value;
      const dark =
        pickRule(
          rules,
          (c) => c.colorMode === "dark" && c.minWidth === undefined && c.scope === undefined,
        ) ?? light;
      return `${doc}    public static let ${identifier}: Color = dsColor(light: ${JSON.stringify(String(light))}, dark: ${JSON.stringify(String(dark))})`;
    }

    if (category === "space" || category === "radius" || category === "layout") {
      const points = parseLengthToPoints(token.value);
      if (points !== undefined) {
        return `${doc}    public static let ${identifier}: CGFloat = ${points}`;
      }
    }

    const isNum = typeof token.value === "number";
    const swiftType = isNum ? "Double" : "String";
    const val = isNum ? String(token.value) : JSON.stringify(token.value);
    return `${doc}    public static let ${identifier}: ${swiftType} = ${val}`;
  });
  const body = lines.length > 0 ? `\n${lines.join("\n")}\n` : "\n";
  return `// Generated by @design-system/tokens. Do not edit.\n${SWIFT_COLOR_PRELUDE}\npublic enum DesignSystemTokens {${body}}\n`;
}

export function generate(): void {
  const typography = resolveTypography(tokens);
  const fontFiles = readdirSync(fontSourceDir, {
    recursive: true,
    withFileTypes: true,
  })
    .filter((entry) => entry.isFile() && /\.(ttf|otf)$/i.test(entry.name))
    .map((entry) => join(entry.parentPath, entry.name));
  const fontLicenses = readdirSync(fontSourceDir, {
    recursive: true,
    withFileTypes: true,
  }).filter((entry) => entry.isFile() && entry.name === "OFL.txt");
  if (fontFiles.length === 0)
  validateTypographyFontFiles(typography, fontFiles);

  // Runs before `tsc`, so it owns the whole dist/ tree.
  rmSync(join(pkgRoot, "dist"), { recursive: true, force: true });
  mkdirSync(webDir, { recursive: true });
  mkdirSync(iosDir, { recursive: true });
  mkdirSync(fontOutputDir, { recursive: true });

  writeFileSync(join(webDir, "tokens.css"), renderCss(tokens), "utf8");
  writeFileSync(join(iosDir, "Tokens.swift"), renderSwift(tokens), "utf8");
  writeFileSync(
    join(iosDir, "Typography.swift"),
    renderTypographySwift(typography),
    "utf8",
  );
  for (const file of fontFiles)
    copyFileSync(file, join(fontOutputDir, file.split("/").pop()!));
  for (const license of fontLicenses) {
    const family = license.parentPath.split("/").pop()!;
    copyFileSync(
      join(license.parentPath, license.name),
      join(fontOutputDir, `${family}-OFL.txt`),
    );
  }
  copyFileSync(
    join(iosSourceDir, "TokenFonts.swift"),
    join(iosDir, "TokenFonts.swift"),
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  generate();
  const count = Object.keys(tokens).length;
  console.log(
    `@design-system/tokens: generated CSS + Swift for ${count} token(s)`,
  );
}
