import type { Tokens } from "./types.js";

export interface NativeTypography {
  role: string;
  fontName: string;
  pointSize: number;
  weight: number;
  lineHeightMultiplier: number;
}

const FONT_NAMES: Record<string, Record<number, string>> = {
  "Bricolage Grotesque": {
    400: "BricolageGrotesque-96ptExtraBold_Regular",
    600: "BricolageGrotesque-96ptExtraBold_SemiBold",
    800: "BricolageGrotesque-96ptExtraBold_ExtraBold",
  },
  "Public Sans": {
    400: "PublicSansRoman-Regular",
    500: "PublicSansRoman-Medium",
    700: "PublicSansRoman-Bold",
  },
  "IBM Plex Mono": {
    400: "IBMPlexMono-Regular",
    500: "IBMPlexMono-Medium",
  },
};

export function parseTypographyToken(
  role: string,
  value: string,
): NativeTypography {
  const match = value.match(
    /^normal normal (\d{3}) ([0-9]+(?:\.[0-9]+)?)(rem|px)\/([0-9]+(?:\.[0-9]+)?) '([^']+)'(?:,\s*.+)?$/,
  );
  if (!match) throw new Error(`type.${role}: unsupported typography shorthand`);

  const [, weightText, sizeText, unit, lineHeightText, family] = match;
  const weight = Number(weightText);
  const fontName = FONT_NAMES[family!]?.[weight];
  if (!FONT_NAMES[family!])
    throw new Error(`type.${role}: unsupported font family "${family}"`);
  if (!fontName)
    throw new Error(
      `type.${role}: unsupported font weight ${weight} for "${family}"`,
    );
  const pointSize = Number(sizeText) * (unit === "rem" ? 16 : 1);
  const lineHeightMultiplier = Number(lineHeightText);
  if (pointSize <= 0 || lineHeightMultiplier <= 0) {
    throw new Error(`type.${role}: font size and line height must be positive`);
  }

  return { role, fontName, pointSize, weight, lineHeightMultiplier };
}

export function resolveTypography(tokens: Tokens): NativeTypography[] {
  return Object.entries(tokens)
    .filter(([name]) => name.startsWith("type."))
    .map(([name, token]) => {
      if (typeof token.value !== "string") {
        throw new Error(`${name}: typography value must be a string`);
      }
      return parseTypographyToken(name.slice("type.".length), token.value);
    });
}

export function validateTypographyFontFiles(
  styles: NativeTypography[],
  fontFiles: string[],
): void {
  if (fontFiles.length === 0) {
    throw new Error("No licensed iOS font files found under src/fonts");
  }
  for (const style of styles) {
    const familyPrefix = style.fontName.startsWith("PublicSansRoman-")
      ? "publicsans"
      : style.fontName.split(/[-_]/)[0]!.toLowerCase();
    if (!fontFiles.some((file) => file.toLowerCase().includes(familyPrefix))) {
      throw new Error(`type.${style.role}: no source font file for ${style.fontName}`);
    }
  }
}

export function renderTypographySwift(styles: NativeTypography[]): string {
  const entries = styles.map((style) => {
    const identifier = style.role.replace(
      /-([a-z0-9])/g,
      (_match, letter: string) => letter.toUpperCase(),
    );
    return `    public static let ${identifier} = DesignSystemTypography(fontName: ${JSON.stringify(style.fontName)}, pointSize: ${style.pointSize}, weight: ${style.weight}, lineHeightMultiplier: ${style.lineHeightMultiplier})`;
  });
  return [
    "// Generated by @design-system/tokens. Do not edit.",
    "",
    "public struct DesignSystemTypography: Equatable {",
    "    public let fontName: String",
    "    public let pointSize: Double",
    "    public let weight: Int",
    "    public let lineHeightMultiplier: Double",
    "",
    "    public init(fontName: String, pointSize: Double, weight: Int, lineHeightMultiplier: Double) {",
    "        self.fontName = fontName",
    "        self.pointSize = pointSize",
    "        self.weight = weight",
    "        self.lineHeightMultiplier = lineHeightMultiplier",
    "    }",
    "}",
    "",
    "public enum DesignSystemTypographyTokens {",
    ...entries,
    "}",
    "",
  ].join("\n");
}
