import type {
  TokenManifest,
  TokenManifestGroup,
} from "@design-system/tokens";
// Generated by the tokens package (`pnpm --filter @design-system/tokens generate`).
import data from "@design-system/tokens/manifest";

export const manifest = data as TokenManifest;

export function getGroup(
  name: string,
  kind?: "primitive" | "semantic",
): TokenManifestGroup {
  const group = manifest.groups.find(
    (g) => g.name === name && (kind ? g.kind === kind : true),
  );
  if (!group) {
    throw new Error(
      `Token group "${name}"${kind ? ` (${kind})` : ""} not found in manifest. Did you run the generator?`,
    );
  }
  return group;
}
