/**
 * Components generator — emits the iOS Swift projection only. The web output
 * (dist/web/*.js + .d.ts) is produced by `tsc` from src/.
 *
 *   - dist/ios/DesignSystemComponents/Components.swift   namespace stub
 *
 * Deterministic; valid even with no real components authored.
 */
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");
const iosDir = join(pkgRoot, "dist", "ios", "DesignSystemComponents");

const COMPONENTS: string[] = ["Placeholder"];

export function renderSwift(components: string[]): string {
  const names = components.map((c) => `    // ${c}`).join("\n");
  const body = names ? `\n${names}\n` : "\n";
  return `// Generated by @design-system/components. Do not edit.\nimport DesignSystemTokens\nimport DesignSystemIcons\n\npublic enum DesignSystemComponents {${body}}\n`;
}

export function generate(): void {
  rmSync(join(pkgRoot, "dist", "ios"), { recursive: true, force: true });
  mkdirSync(iosDir, { recursive: true });
  writeFileSync(join(iosDir, "Components.swift"), renderSwift(COMPONENTS), "utf8");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  generate();
  console.log(
    `@design-system/components: generated Swift stub for ${COMPONENTS.length} component(s)`,
  );
}
