/**
 * Components generator — emits the iOS Swift projection only. The web output
 * (dist/web/*.js + .d.ts) is produced by `tsc` from src/.
 *
 *   - dist/ios/DesignSystemComponents/Components.swift   namespace stub
 *
 * Deterministic; valid even with no real components authored.
 */
import {
  mkdirSync,
  rmSync,
  writeFileSync,
  copyFileSync,
  readdirSync,
  existsSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");
const iosDir = join(pkgRoot, "dist", "ios", "DesignSystemComponents");
const webDir = join(pkgRoot, "dist", "web");

const COMPONENTS: string[] = ["Placeholder", "Text", "Button", "Link"];

export function renderSwift(components: string[]): string {
  const names = components.map((c) => `    // ${c}`).join("\n");
  const body = names ? `\n${names}\n` : "\n";
  return `// Generated by @design-system/components. Do not edit.\nimport DesignSystemTokens\nimport DesignSystemIcons\n\npublic enum DesignSystemComponents {${body}}\n`;
}

export function generate(): void {
  rmSync(join(pkgRoot, "dist"), { recursive: true, force: true });
  mkdirSync(iosDir, { recursive: true });
  mkdirSync(webDir, { recursive: true });
  writeFileSync(
    join(iosDir, "Components.swift"),
    renderSwift(COMPONENTS),
    "utf8",
  );
  const iosSourceDir = join(here, "ios");
  const sources = existsSync(iosSourceDir)
    ? readdirSync(iosSourceDir, {
        recursive: true,
        withFileTypes: true,
      }).filter((entry) => entry.isFile() && entry.name.endsWith(".swift"))
    : [];
  for (const source of sources) {
    copyFileSync(
      join(source.parentPath, source.name),
      join(iosDir, source.name),
    );
  }
  copyFileSync(join(here, "Text.module.css"), join(webDir, "Text.module.css"));
  copyFileSync(
    join(here, "Button.module.css"),
    join(webDir, "Button.module.css"),
  );
  copyFileSync(join(here, "Link.module.css"), join(webDir, "Link.module.css"));
}

if (import.meta.url === `file://${process.argv[1]}`) {
  generate();
  console.log(
    `@design-system/components: generated Swift stub for ${COMPONENTS.length} component(s) and copied CSS Module assets`,
  );
}
