/**
 * Icon generator. Reads src/svg/*.svg and emits:
 *   - dist/web/index.js   typed React components (fill: currentColor — no hardcoded colour)
 *   - dist/web/index.d.ts
 *   - dist/ios/DesignSystemIcons/Icons.swift   namespace stub
 *
 * Deterministic: same SVGs -> byte-identical output. Empty svg dir -> valid
 * empty barrel + Swift stub, exit 0.
 */
import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { tokens } from "@design-system/tokens";

// Proves the one-way dependency resolves at build time: icons -> tokens.
// If a dedicated icon-colour token exists we reference it; otherwise fall back
// to `currentColor`. Either way, no hardcoded colour value.
const FILL = "iconColor" in tokens ? "var(--ds-icon-color)" : "currentColor";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");
const svgDir = join(here, "svg");
const webDir = join(pkgRoot, "dist", "web");
const iosDir = join(pkgRoot, "dist", "ios", "DesignSystemIcons");

interface Icon {
  componentName: string;
  viewBox: string;
  paths: string[];
}

export function componentNameFor(fileName: string): string {
  const base = fileName.replace(/\.svg$/i, "");
  const pascal = base
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((s) => s[0]!.toUpperCase() + s.slice(1))
    .join("");
  return `${pascal}Icon`;
}

export function parseSvg(fileName: string, source: string): Icon {
  const viewBox = /viewBox="([^"]+)"/.exec(source)?.[1] ?? "0 0 24 24";
  const paths = [...source.matchAll(/<path\b[^>]*\bd="([^"]+)"[^>]*\/?>/g)].map(
    (m) => m[1]!,
  );
  return { componentName: componentNameFor(fileName), viewBox, paths };
}

export function renderComponentJs(icon: Icon): string {
  const children = icon.paths
    .map((d) => `createElement("path", { d: ${JSON.stringify(d)} })`)
    .join(", ");
  return `export function ${icon.componentName}(props) {
  return createElement(
    "svg",
    { viewBox: ${JSON.stringify(icon.viewBox)}, fill: ${JSON.stringify(FILL)}, width: "1em", height: "1em", ...props },
    ${children || "null"}
  );
}`;
}

export function renderIndexJs(icons: Icon[]): string {
  if (icons.length === 0) {
    return `// Generated by @design-system/icons. Do not edit.\nexport {};\n`;
  }
  return `// Generated by @design-system/icons. Do not edit.
import { createElement } from "react";

${icons.map(renderComponentJs).join("\n\n")}
`;
}

export function renderIndexDts(icons: Icon[]): string {
  if (icons.length === 0) {
    return `// Generated by @design-system/icons. Do not edit.\nexport {};\n`;
  }
  return `// Generated by @design-system/icons. Do not edit.
import type { FC, SVGProps } from "react";

${icons
  .map((i) => `export declare const ${i.componentName}: FC<SVGProps<SVGSVGElement>>;`)
  .join("\n")}
`;
}

export function renderSwift(icons: Icon[]): string {
  const names = icons.map((i) => `    // ${i.componentName}`).join("\n");
  const body = names ? `\n${names}\n` : "\n";
  return `// Generated by @design-system/icons. Do not edit.\nimport DesignSystemTokens\n\npublic enum DesignSystemIcons {${body}}\n`;
}

export function loadIcons(): Icon[] {
  let files: string[] = [];
  try {
    files = readdirSync(svgDir).filter((f) => f.toLowerCase().endsWith(".svg"));
  } catch {
    files = [];
  }
  return files
    .sort()
    .map((f) => parseSvg(f, readFileSync(join(svgDir, f), "utf8")));
}

export function generate(): void {
  const icons = loadIcons();
  rmSync(join(pkgRoot, "dist"), { recursive: true, force: true });
  mkdirSync(webDir, { recursive: true });
  mkdirSync(iosDir, { recursive: true });
  writeFileSync(join(webDir, "index.js"), renderIndexJs(icons), "utf8");
  writeFileSync(join(webDir, "index.d.ts"), renderIndexDts(icons), "utf8");
  writeFileSync(join(iosDir, "Icons.swift"), renderSwift(icons), "utf8");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const icons = loadIcons();
  generate();
  console.log(`@design-system/icons: generated ${icons.length} icon component(s)`);
}
